name: Generate 3D Contributions Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Atualiza a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: davimotarodrigues
          outputs: |
            output/github-contribution-grid-3d.svg?palette=github-dark

      - uses: actions/upload-artifact@v3
        with:
          name: snake-artifacts
          path: output/**
