name: Generate Snake Anim

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: davimotarodrigues
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake animation to output
        run: |
          mkdir -p output
          cp dist/*.svg output
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output
          git commit -m "Update snake animation" || echo "Nothing to commit"
          git push
