name: Generate Snake

on:
  schedule: 
    - cron: "0 */12 * * *" # A cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Commit and Push Snake Animation
        run: |
          mkdir -p output
          cp dist/*.svg output/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Generate snake animation" || echo "No changes to commit"
          git push
