name: Wave Skyline Contributions

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Wave Skyline (Light Mode)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 0
          config_output: svg
      - name: Move files
        run: |
          mkdir -p output
          mv metrics.svg output/github-contribution-grid-wave-skyline.svg
